[package]
name = "avicenna"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
getrandom = { version = "0.3", features = ["wasm_js"] }
macroquad = "0.4.14"
ndarray = "0.16.1"
#ndarray-rand = "0.15.0"
rand = "0.9.1"
